name: "Beautiful, lonely book seeks marketing genius"
description: "A marketing challenge for a brave, smart team"

url: http://localhost:4000
baseurl: /wieisdit

paginate: 10

markdown: kramdown
permalink: pretty
highlighter: pygments